# Generated by Django 5.1.2 on 2024-10-18 09:29

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=markdownx.models.MarkdownxField(editable=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_de",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_en",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_es",
            field=markdownx.models.MarkdownxField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="folder",
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="article",
            name="subfolder",
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_de",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_en",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_es",
            field=models.CharField(editable=False, max_length=256, null=True),
        ),
    ]
