# Generated by Django 5.1.2 on 2024-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_body_alter_article_body_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False,
                help_text="If featured it will be showed in home ",
                verbose_name="Featured article",
            ),
        ),
    ]
