# Generated by Django 5.1.2 on 2024-10-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_de",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="custom_title_es",
            new_name="title_es",
        ),
        migrations.RenameField(
            model_name="pagelink",
            old_name="external_url",
            new_name="url",
        ),
    ]
